# Generated by Django 3.2.4 on 2021-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileMan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
